version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 14
  build:
    commands:
     - cd client
     - npm i
     - npm run build


artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: 'client/dist'
